# Generated by Django 5.0.7 on 2024-07-17 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('fecha', models.DateField()),
                ('nombre_conductor', models.CharField(max_length=100)),
                ('numero_guia', models.CharField(max_length=50)),
                ('lugar_carga', models.CharField(max_length=200)),
                ('kilometraje', models.IntegerField()),
                ('total_carga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
